version: '3.7'

services:
  web:
    build: .
    volumes: 
      - .:/toy_app
    ports:
      - 3000:3000
      - 3001:3001
      - 3002:3002
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
    command: bundle exec rails s -b '0.0.0.0' -p 3000

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  bundle_cache:
